name: "Install CI Dependencies"
description: "Install Python dependencies for CI workflows using uv"

inputs:
  python_version:
    description: "Python version to use"
    required: false
    default: "3.12"
  use_oldest:
    description: "Whether to use oldest compatible versions (for testing min version support)"
    required: false
    default: "false"
  use_commit_pin:
    description: "Whether to use Lightning commit pinning via UV_OVERRIDE"
    required: false
    default: "true"
  show_pip_list:
    description: "Whether to show package list output after installations"
    required: false
    default: "false"
runs:
  using: "composite"
  steps:
    - name: Install uv and set Python version
      uses: astral-sh/setup-uv@v7
      with:
        python-version: ${{ inputs.python_version }}
        activate-environment: true
        enable-cache: true

    # Detect if torch nightly is configured
    - name: Check torch nightly configuration
      id: torch-config
      shell: bash
      run: |
        NIGHTLY_FILE="requirements/ci/torch-nightly.txt"
        if [[ -f "${NIGHTLY_FILE}" ]]; then
          TORCH_VERSION=$(grep -v '^#' "${NIGHTLY_FILE}" | grep -v '^$' | head -1 || true)
          if [[ -n "${TORCH_VERSION}" ]]; then
            echo "torch_nightly=true" >> $GITHUB_OUTPUT
            echo "torch_version=${TORCH_VERSION}" >> $GITHUB_OUTPUT
            echo "Torch nightly detected: ${TORCH_VERSION}"
          else
            echo "torch_nightly=false" >> $GITHUB_OUTPUT
            echo "No torch nightly configured"
          fi
        else
          echo "torch_nightly=false" >> $GITHUB_OUTPUT
          echo "No torch-nightly.txt found"
        fi

    # Pre-install torch nightly if configured (before lock file installation)
    # Note: Skip on macOS ARM64 - nightly +cpu wheels are only built for x86_64
    # macOS ARM uses MPS acceleration, not CPU-only builds
    - name: Pre-install torch nightly
      if: steps.torch-config.outputs.torch_nightly == 'true' && runner.os != 'macOS'
      shell: bash
      run: |
        echo "Pre-installing torch nightly: ${{ steps.torch-config.outputs.torch_version }}+cpu"
        uv pip install --prerelease=allow "torch==${{ steps.torch-config.outputs.torch_version }}+cpu" \
          --index-url https://download.pytorch.org/whl/nightly/cpu

    # Single command installation of FTS and all dependencies
    # - UV_OVERRIDE: applies Lightning commit pin from overrides.txt
    # - When nightly: filter torch from requirements file
    # - When stable: use --torch-backend=cpu to ensure CPU variant
    - name: Install FTS and all dependencies
      shell: bash
      env:
        UV_OVERRIDE: ${{ inputs.use_commit_pin == 'true' && format('{0}/requirements/ci/overrides.txt', github.workspace) || '' }}
      run: |
        if [[ "${{ inputs.use_oldest }}" == "true" ]]; then
          REQ_FILE="requirements/ci/requirements-oldest.txt"
          echo "Installing with oldest versions..."
        else
          REQ_FILE="requirements/ci/requirements.txt"
          echo "Installing with latest versions..."
        fi

        # When torch nightly is configured, requirements.txt already has torch filtered
        # (done during lock file generation). Otherwise use --torch-backend for CPU variant.
        # Note: On macOS ARM64, torch nightly +cpu isn't available, so we need --torch-backend=auto
        # to get regular torch with MPS support
        if [[ "${{ steps.torch-config.outputs.torch_nightly }}" == "true" ]]; then
          if [[ "${{ runner.os }}" == "macOS" ]]; then
            # macOS: torch nightly +cpu not available for ARM64, install regular torch
            INSTALL_CMD="uv pip install -e . -r ${REQ_FILE} --torch-backend=auto"
          else
            # Linux/Windows: torch nightly already pre-installed
            INSTALL_CMD="uv pip install -e . -r ${REQ_FILE}"
          fi
        else
          INSTALL_CMD="uv pip install -e . -r ${REQ_FILE} --torch-backend=cpu"
        fi

        echo "Running: ${INSTALL_CMD}"
        echo "  UV_OVERRIDE=${UV_OVERRIDE:-'(not set)'}"
        ${INSTALL_CMD}

    - name: Show package list
      if: inputs.show_pip_list == 'true'
      shell: bash
      run: |
        uv pip list
