#!/usr/bin/env python3
"""Re-measure how each renderer treats the constructs this skill has an opinion about.

The compatibility table in references/platform-matrix.md is a measurement with an expiry date: it
describes the renderer versions installed when it was taken, and a parser release can invalidate any
row. Rather than ask a reader to trust it, this regenerates it.

Engines are probed only if importable, so this degrades to whatever is present:
  Sphinx/MyST   needs myst-parser        (pip install myst-parser)
  MkDocs        needs pymdown-extensions (pip install markdown pymdown-extensions)
  GitHub        needs an authenticated `gh` CLI (renders through GitHub's real markdown API)

  probe_renderers.py            print the measured matrix
  probe_renderers.py --report   also flag cells that disagree with what the skill records

Run each engine from an interpreter that has it. When engines live in different environments, run
this once per environment; the matrix prints only the engines it could reach.
"""

from __future__ import annotations

import argparse
import html as html_mod
import json
import subprocess
import sys

# Constructs the skill makes a claim about. Keep the corpus small: every row here is a sentence in
# SKILL.md, and a construct nobody is advised about does not need measuring.
# Each construct declares the exact body that should reach the math engine. A verdict is then a
# comparison rather than a heuristic: "verbatim" means the renderer handed the engine what the author
# wrote, "altered" means it changed it, "no-math" means it never recognised it as math at all.
# expected=None means no math span should be produced (the correct outcome for prose).
CORPUS = {
    "inline":              ("A $x^2$ B", "x^2"),
    "inline-subscripts":   ("A $a_1 + b_2$ B", "a_1 + b_2"),
    "inline-loose":        ("A $ x^2 $ B", "x^2"),
    "gh-backticks":        ("A $`x^2`$ B", "x^2"),
    "raw-angle":           ("A $x<y$ B", "x<y"),
    "lt-macro":            ("A $x \\lt y$ B", "x \\lt y"),
    "block-1line-2bs":     ("$$\\begin{aligned}a &= b \\\\ c &= d\\end{aligned}$$",
                            "\\begin{aligned}a &= b \\\\ c &= d\\end{aligned}"),
    "block-multiline-2bs": ("$$\n\\begin{aligned}\na &= b \\\\\nc &= d\n\\end{aligned}\n$$",
                            "\\begin{aligned} a &= b \\\\ c &= d \\end{aligned}"),
    "block-multiline-4bs": ("$$\n\\begin{aligned}\na &= b \\\\\\\\\nc &= d\n\\end{aligned}\n$$",
                            "\\begin{aligned} a &= b \\\\\\\\ c &= d \\end{aligned}"),
    "bare-amsmath":        ("\\begin{align}\na &= b\n\\end{align}", "\\begin{align} a &= b \\end{align}"),
    "underbrace-single":   ("$$\n\\begin{aligned}\nL &= \\underbrace{a}_{r} \\\\\n  &+ b\n\\end{aligned}\n$$",
                            "\\begin{aligned} L &= \\underbrace{a}_{r} \\\\ &+ b \\end{aligned}"),
    "underbrace-pair":     ("$$\n\\begin{aligned}\nL &= \\underbrace{a}_{r} \\\\\n  &+ \\underbrace{b}_{s}\n\\end{aligned}\n$$",
                            "\\begin{aligned} L &= \\underbrace{a}_{r} \\\\ &+ \\underbrace{b}_{s} \\end{aligned}"),
    "emphasis-open-then-close": ("$$\n\\begin{aligned}\na &= \\hat{x}_i \\\\\nb &= W_{enc}\n\\end{aligned}\n$$",
                            "\\begin{aligned} a &= \\hat{x}_i \\\\ b &= W_{enc} \\end{aligned}"),
    "prose-then-codespan": ("Set $HOME then run `echo $PATH`.", None),
    "spacing-command":     ("$$\na \\, b\n$$", "a \\, b"),
    "tight-open-delim":    ("the top-$q$ of it", "q"),
    "shell-var-pair":      ("Set $HOME and $PATH now.", None),
    "shell-var-adjacent":  ("check $TMPDIR/$SLURM_JOB_ID in the log", None),
}

# What the skill records. Populated by measurement (--json), never by reasoning. The config assumed
# is the one Step 1 of SKILL.md prescribes: dollarmath+amsmath for MyST, arithmatex for MkDocs.
RECORDED: dict[str, dict[str, str]] = {
    # Regenerated by measurement, not by reasoning: run --json in each environment that has an
    # engine and paste the result here. Engines at time of writing:
    #   github: github.com markdown API (live)
    #   mkdocs: python-markdown 3.10.3 / pymdown-extensions 11.0.2
    #   myst: myst-parser 5.1.0
    # "verbatim" is renderer FIDELITY, not authoring advice: arithmatex reproduces four
    # backslashes faithfully, and four backslashes is still wrong LaTeX. SKILL.md says what to
    # write; this records what each engine does with it.
    "myst": {
        "inline": "verbatim",
        "inline-subscripts": "verbatim",
        "inline-loose": "verbatim",
        "gh-backticks": "altered",
        "raw-angle": "verbatim",
        "lt-macro": "verbatim",
        "block-1line-2bs": "verbatim",
        "block-multiline-2bs": "verbatim",
        "block-multiline-4bs": "verbatim",
        "bare-amsmath": "verbatim",
        "underbrace-single": "verbatim",
        "underbrace-pair": "verbatim",
        "emphasis-open-then-close": "verbatim",
        "prose-then-codespan": "altered",
        "spacing-command": "verbatim",
        "tight-open-delim": "verbatim",
        "shell-var-pair": "altered",
        "shell-var-adjacent": "altered",
    },
    "mkdocs": {
        "inline": "verbatim",
        "inline-subscripts": "verbatim",
        "inline-loose": "no-math",
        "gh-backticks": "no-math",
        "raw-angle": "verbatim",
        "lt-macro": "verbatim",
        "block-1line-2bs": "verbatim",
        "block-multiline-2bs": "verbatim",
        "block-multiline-4bs": "verbatim",
        "bare-amsmath": "verbatim",
        "underbrace-single": "verbatim",
        "underbrace-pair": "verbatim",
        "emphasis-open-then-close": "verbatim",
        "prose-then-codespan": "no-math",
        "spacing-command": "verbatim",
        "tight-open-delim": "verbatim",
        "shell-var-pair": "no-math",
        "shell-var-adjacent": "altered",
    },
    "github": {
        "inline": "verbatim",
        "inline-subscripts": "verbatim",
        "inline-loose": "no-math",
        "gh-backticks": "verbatim",
        "raw-angle": "altered",
        "lt-macro": "verbatim",
        "block-1line-2bs": "altered",
        "block-multiline-2bs": "verbatim",
        "block-multiline-4bs": "altered",
        "bare-amsmath": "no-math",
        "underbrace-single": "verbatim",
        "underbrace-pair": "altered",
        "emphasis-open-then-close": "altered",
        "prose-then-codespan": "no-math",
        "spacing-command": "altered",
        "tight-open-delim": "no-math",
        "shell-var-pair": "no-math",
        "shell-var-adjacent": "no-math",
    },
}


def _norm(s: str) -> str:
    """Collapse whitespace so multi-line and one-line forms of the same body compare equal."""
    return " ".join(s.split())


def classify(name: str, body: str | None) -> str:
    """Compare what reached the math engine against what the author wrote.

    The body is unescaped exactly once. A renderer writing '&' as '&amp;' in its HTML is correct
    encoding, and the math engine reading textContent sees '&'. A renderer that emits '&amp;lt;' is
    encoding twice, so the engine really does receive the string '&lt;' instead of '<' - that one is
    corruption, and the single unescape is what tells the two cases apart.
    """
    expected = CORPUS[name][1]
    if body is not None:
        body = html_mod.unescape(body)
    if body is None:
        return "no-math" if expected is not None else "no-math"
    if expected is None:
        return "altered"  # produced math where the author wrote prose
    return "verbatim" if _norm(body) == _norm(expected) else "altered"


def probe_myst():
    try:
        import myst_parser
        from markdown_it.renderer import RendererHTML
        from myst_parser.config.main import MdParserConfig
        from myst_parser.parsers.mdit import create_md_parser
    except ImportError:
        return None, None
    import re
    md = create_md_parser(
        MdParserConfig(enable_extensions={"dollarmath", "amsmath"}), RendererHTML
    )
    out = {}
    for name, (src, _exp) in CORPUS.items():
        html = md.render(src)
        m = re.search(r'class="math[^"]*"[^>]*>(.*?)</(?:span|div)>', html, re.S)
        out[name] = classify(name, m.group(1) if m else None)
    return out, f"myst-parser {myst_parser.__version__}"


def probe_mkdocs():
    try:
        import markdown
        import pymdownx
    except ImportError:
        return None, None
    import re
    md = markdown.Markdown(extensions=["pymdownx.arithmatex"])
    out = {}
    for name, (src, _exp) in CORPUS.items():
        md.reset()
        html = md.convert(src)
        m = re.search(r'type="math/tex[^"]*">(.*?)</script>', html, re.S)
        out[name] = classify(name, m.group(1) if m else None)
    return out, f"python-markdown {markdown.__version__} / pymdown-extensions {pymdownx.__version__}"


def probe_github():
    import re
    try:
        subprocess.run(["gh", "auth", "status"], capture_output=True, check=True)
    except (OSError, subprocess.CalledProcessError):
        return None, None
    out = {}
    for name, (src, _exp) in CORPUS.items():
        try:
            r = subprocess.run(
                ["gh", "api", "-X", "POST", "/markdown", "-f", "mode=gfm", "-f", f"text={src}"],
                capture_output=True, text=True, check=True,
            )
        except subprocess.CalledProcessError:
            return None, None
        m = re.search(r"<math-renderer[^>]*>(.*?)</math-renderer>", r.stdout, re.S)
        body = m.group(1) if m else None
        if body is not None:
            body = body.strip("$").strip()
        out[name] = classify(name, body)
    return out, "github.com markdown API (live)"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--report", action="store_true", help="flag disagreements with the recorded table")
    ap.add_argument("--json", action="store_true", help="emit machine-readable results")
    args = ap.parse_args()

    results, versions = {}, {}
    for key, fn in (("myst", probe_myst), ("mkdocs", probe_mkdocs), ("github", probe_github)):
        res, ver = fn()
        if res is None:
            print(f"# {key}: not available in this environment, skipped", file=sys.stderr)
            continue
        results[key], versions[key] = res, ver

    if not results:
        print("no renderers available; install myst-parser or pymdown-extensions, or authenticate gh")
        return 1

    if args.json:
        print(json.dumps({"versions": versions, "results": results}, indent=2))
        return 0

    engines = list(results)
    width = max(len(c) for c in CORPUS) + 2
    print("construct".ljust(width) + "".join(e.ljust(12) for e in engines))
    print("-" * (width + 12 * len(engines)))
    for name in CORPUS:
        print(name.ljust(width) + "".join(results[e][name].ljust(12) for e in engines))
    print()
    for e in engines:
        print(f"  {e}: {versions[e]}")

    rc = 0
    if args.report:
        drift = [
            (e, n, RECORDED[e][n], results[e][n])
            for e in engines for n in CORPUS
            if n in RECORDED.get(e, {}) and RECORDED[e][n] != results[e][n]
        ]
        print()
        if not any(RECORDED.values()):
            print("no baseline recorded yet; paste --json output into RECORDED to arm drift detection")
        elif not drift:
            print("matrix agrees with what the skill records")
        else:
            for e, n, was, now in drift:
                print(f"DRIFT {e}/{n}: skill records '{was}', measured '{now}'")
            print("\nUpdate references/platform-matrix.md and the affected guidance in SKILL.md.")
            rc = 1
    return rc


if __name__ == "__main__":
    sys.exit(main())
