#!/usr/bin/env python3
"""Refuse edits to skills vendored from a shared master.

WHAT THIS IS NOT. It does not detect that the shared master has moved ahead of this repo's copy. That check needs the
master, so it can only run where the master is available, and it is `sync-shared-skills.sh status` in the maintainer's
private admin repo. Trying to do it here would mean either a network call on every commit or a private-path dependency
that fails on a clean public clone, and a pre-commit hook that fails on a clean checkout teaches contributors to pass
`--no-verify`, which disables every other hook too. That trade is not worth making for a condition no contributor can
act on.

WHAT IT IS. The other half, and the half that belongs in the consuming repo: an offline, dependency-free assertion that
these files are MANAGED ELSEWHERE and are not editable here. A local edit to a vendored skill is silently discarded by
the next `sync-shared-skills.sh push`, so the person who wrote it loses the work and nobody finds out why. That failure
needs no master to detect, and unlike drift against the master, anyone who trips it can act on it: send the change
upstream.

The manifest cannot go stale in a harmful direction. It is regenerated by the same command that legitimately changes
these files, so the only way for a hash to disagree is the case being caught.
"""

from __future__ import annotations

import argparse
import hashlib
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
UPSTREAM = "https://github.com/speediedan/skills"

# The neutral primary. Repos migrating to the agent-neutral layout vendor skills to
# `.agents/skills/`; `.claude/skills/` remains as a compat copy through the transition
# (see the agent-neutrality coordination doc). The checker serves both trees: one manifest
# per tree, each regenerated by the same sync step that legitimately changes its files.
DEFAULT_SKILLS_DIR = Path(".agents/skills")
LEGACY_SKILLS_DIR = Path(".claude/skills")


def _sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def _check_tree(skills_dir: Path) -> tuple[int, int]:
    """Verify one vendored tree against its manifest.

    Returns (checked, failures).
    """
    manifest = REPO / skills_dir / ".shared-skills.sha256"
    if not manifest.exists():
        # A missing manifest is a failure, not a skip. A skip here would be indistinguishable from a
        # clean pass, which is the ambiguity this whole check exists to remove.
        print(f"error: {manifest.relative_to(REPO)} is missing, so vendored skills cannot be verified.")
        print("       If a vendored skill was removed deliberately, drop its line from the manifest.")
        return 0, 1

    edited: list[str] = []
    missing: list[str] = []
    checked = 0

    for line in manifest.read_text().splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        expected, _, rel = line.partition("  ")
        target = REPO / rel
        if not target.exists():
            missing.append(rel)
            continue
        checked += 1
        if _sha256(target) != expected:
            edited.append(rel)

    if missing:
        print("error: vendored skill named in the manifest is absent:")
        for rel in missing:
            print(f"       {rel}")
        return checked, 1

    if edited:
        print("error: a vendored skill was modified in this repo.")
        print("")
        for rel in edited:
            print(f"       {rel}")
        print("")
        print(f"These files are vendored from {UPSTREAM} and are overwritten wholesale by the next")
        print("`sync-shared-skills.sh push`, so an edit made here is discarded without warning.")
        print("")
        print("  To change the skill      open a PR against the upstream repo, then take the push.")
        print("  To take an upstream fix  run `sync-shared-skills.sh push --repo <this repo> --yes`,")
        print("                           which rewrites the file AND this manifest together.")
        return checked, 1

    # Announce what was verified. A silent pass is indistinguishable from a hook that did not run,
    # and that ambiguity has cost this project real time more than once.
    print(f"vendored skills unmodified: {checked} file(s) match {manifest.relative_to(REPO)}")
    return checked, 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Refuse edits to skills vendored from a shared master.")
    parser.add_argument(
        "--skills-dir",
        action="append",
        default=[],
        help="Vendored skills tree to check, relative to the repo root. "
        f"Repeatable. Default: {DEFAULT_SKILLS_DIR} (plus {LEGACY_SKILLS_DIR} if present).",
    )
    args = parser.parse_args(argv)

    dirs = [Path(d) for d in args.skills_dir] or [DEFAULT_SKILLS_DIR]
    if not args.skills_dir and (REPO / LEGACY_SKILLS_DIR).is_dir():
        # Transition compat: a repo that still carries the old tree gets both checked without
        # having to name either. Repos that finished the migration check only the neutral tree.
        dirs.append(LEGACY_SKILLS_DIR)

    total = 0
    failed = 0
    for d in dirs:
        checked, rc = _check_tree(d)
        total += checked
        failed += rc
    if failed:
        return 1
    if total == 0:
        print("error: no vendored skill files checked; manifests may be empty.")
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
