#!/usr/bin/env python3
"""Refuse edits to skills vendored from a shared master.

WHAT THIS IS NOT. It does not detect that the shared master has moved ahead of this repo's copy. That check needs the
master, so it can only run where the master is available, and it is `sync-shared-skills.sh status` in the maintainer's
private admin repo. Trying to do it here would mean either a network call on every commit or a private-path dependency
that fails on a clean public clone, and a pre-commit hook that fails on a clean checkout teaches contributors to pass
`--no-verify`, which disables every other hook too. That trade is not worth making for a condition no contributor can
act on.

WHAT IT IS. The other half, and the half that belongs in the consuming repo: an offline, dependency-free assertion that
these files are MANAGED ELSEWHERE and are not editable here. A local edit to a vendored skill is silently discarded by
the next `sync-shared-skills.sh push`, so the person who wrote it loses the work and nobody finds out why. That failure
needs no master to detect, and unlike drift against the master, anyone who trips it can act on it: send the change
upstream.

The manifest cannot go stale in a harmful direction. It is regenerated by the same command that legitimately changes
these files, so the only way for a hash to disagree is the case being caught.
"""

from __future__ import annotations

import hashlib
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
MANIFEST = REPO / ".claude" / "skills" / ".shared-skills.sha256"
UPSTREAM = "https://github.com/speediedan/skills"


def _sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def main() -> int:
    if not MANIFEST.exists():
        # A missing manifest is a failure, not a skip. A skip here would be indistinguishable from a
        # clean pass, which is the ambiguity this whole check exists to remove.
        print(f"error: {MANIFEST.relative_to(REPO)} is missing, so vendored skills cannot be verified.")
        print("       If a vendored skill was removed deliberately, drop its line from the manifest.")
        return 1

    edited: list[str] = []
    missing: list[str] = []
    checked = 0

    for line in MANIFEST.read_text().splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        expected, _, rel = line.partition("  ")
        target = REPO / rel
        if not target.exists():
            missing.append(rel)
            continue
        checked += 1
        if _sha256(target) != expected:
            edited.append(rel)

    if missing:
        print("error: vendored skill named in the manifest is absent:")
        for rel in missing:
            print(f"       {rel}")
        return 1

    if edited:
        print("error: a vendored skill was modified in this repo.")
        print("")
        for rel in edited:
            print(f"       {rel}")
        print("")
        print(f"These files are vendored from {UPSTREAM} and are overwritten wholesale by the next")
        print("`sync-shared-skills.sh push`, so an edit made here is discarded without warning.")
        print("")
        print("  To change the skill      open a PR against the upstream repo, then take the push.")
        print("  To take an upstream fix  run `sync-shared-skills.sh push --repo <this repo> --yes`,")
        print("                           which rewrites the file AND this manifest together.")
        return 1

    # Announce what was verified. A silent pass is indistinguishable from a hook that did not run,
    # and that ambiguity has cost this project real time more than once.
    print(f"vendored skills unmodified: {checked} file(s) match {MANIFEST.relative_to(REPO)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
